#!/bin/bash
# FA01 Node 09 run script (r3) — generated by execution window
rm -rf /tmp/fa_node09
mkdir -p /tmp/fa_node09
cd /tmp/fa_node09
unset HEARTH_URL
export HEARTH_ALLOW_NO_CGROUP=1
export HEARTH_TASK_TIMEOUT_SECS=600
hearth chat '创建一个 Rust 库项目 calcpkg/，按以下顺序严格执行：
1) 用 bash 执行 mkdir -p calcpkg/src
2) 用 write_file 创建 calcpkg/Cargo.toml，内容为 [package] name=calcpkg version=0.1.0 edition=2021
3) 用 write_file 创建 calcpkg/src/lib.rs，其中包含 pub fn shout(s: &str) -> String { s.to_string() }（故意留一个 bug：未实现大写与感叹号），以及测试模块 #[cfg(test)] mod tests { #[test] fn t_shout() { assert_eq!(shout("hi"), "HI!"); } }
4) 用 bash 执行 cargo test --manifest-path calcpkg/Cargo.toml —— 这次测试会失败（受控失败），记录失败输出
5) 用 write_file 修复 calcpkg/src/lib.rs 中的 shout 实现（改为 format!("{}!", s.to_uppercase())），测试保持不变
6) 用 bash 再执行 cargo test --manifest-path calcpkg/Cargo.toml 确认通过
7) 用 write_file 创建 RESULT.txt，内容写 CONTROLLED_FAILURE_RECOVERED
8) 用 bash 执行 cat RESULT.txt 确认。以上步骤完成后立即宣告任务完成（DONE），不要做额外验证' \
  --budget 50 \
  --acceptance 'cmd: cargo test --manifest-path calcpkg/Cargo.toml' \
  --acceptance 'file: calcpkg/src/lib.rs contains to_uppercase' \
  --acceptance 'file: RESULT.txt contains CONTROLLED_FAILURE_RECOVERED'
echo "EXIT_CODE=$?"
